---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
    - shell: rm -rf /tmp/*; true
    - shell: rm -rf /var/log/nginx/*.log
      args:
        removes: /var/log/nginx/access.log
    - file: path=/var/log/mysqld.log state=absent
    - file: path=/home/vagrant/.ansible state=absent
    - file: path=/home/vagrant/.bash_history state=absent
    - file: path=/home/vagrant/.viminfo state=absent
    - file: path=/home/isucon/.mysql_history state=absent
    - file: path=/home/isucon/.bash_history state=absent

    - shell: rm -r /home/isucon/sql/*.old
      args:
        removes: /home/isucon/sql/dummy_users_used.tsv.old

    - shell: rm -r /home/isucon/sql/*.rb
      args:
        removes: /home/isucon/sql/generate_users.rb

    - shell: find /home/isucon/webapp -maxdepth 2 -name 'README.*' -delete

    - file: path=/home/isucon/php/nginx.local.conf state=absent
    - file: path=/home/isucon/php/Procfile state=absent
